### ISSUE TITLE
Package `ember-export-application-global` removed in Ember.js v4.5.0

### ISSUE THREAD

**Issue by MrChocolatine** [DazzlingFugu/ember-cli-embedded#199]
See the release notes:
- https://github.com/ember-cli/ember-cli/releases/tag/v4.5.0

And the relevant pull request:
- https://github.com/ember-cli/ember-cli/pull/9825

Because [we rely on this add-on](https://github.com/DazzlingFugu/ember-cli-embedded/blob/v2.5.0/README.md?plain=1#L59-L60) we will need to add a warning.

**Comment by BlueCutOfficial** [comment]
What kind of warning do you have in mind? Shouldn't we move this from devDeps to dep or add the install in this addon blueprint when updating to Ember 4.5.0?

**Comment by MrChocolatine** [comment]
@BlueCutOfficial 

> What kind of warning do you have in mind? Shouldn't we move this from devDeps to dep or add the install in this addon blueprint when updating to Ember 4.5.0?

I did not have anything specific in mind when writing this, simply "we will need to take care of that".
And yes to what you said.
