### ISSUE TITLE
Kill `config:embedded`

### ISSUE THREAD

**Issue by xcambar** [DazzlingFugu/ember-cli-embedded#4]
Stop using `config:embedded` as a configuration store and instead add a key to `config:environment`, such as `APP.embedded = { /* my config */}`

**Comment by antulik** [comment]
I can see two use-cases here. One we want to merge with ENV and when we don't (to restrict access).

The problem with `APP.embedded = { /* my config */}` is that you would need to have code which chooses value between embedded and global. I don't see why app should differentiate between two configs, all it cares is the most relevant config.

**Comment by xcambar** [comment]
Will you give the fac0e89cd4cce8ba0991b95cebb1aff51e89054e a try?

It keeps the `config:embedded` yet merges its contents back to `config.APP`.

It allows to discriminate original config from startup config (maybe not indispensable, but I feel better with it than without) and most of all:
1. you don't need code that is aware of `config:embedded` and `config:environment`
2. You can customise the rootElement dynamically

Sorry it took so long, btw.

**Comment by antulik** [comment]
is there a good reason why you've added `lodash` dependancy? Can't you use existing libraries to merge?

**Comment by xcambar** [comment]
`Ember.merge` is shallow. Lodash makes a deep merge.

Because we don't want to lose any config, having a deep merge seemed necessary. Do you see any other option?

**Comment by antulik** [comment]
I'm still beginner with ember, but how about `Ember.$.extend`?

**Comment by xcambar** [comment]
Very good idea. I just didn't think about it, thanks for pointing that out.

Code has been updated.

**Comment by antulik** [comment]
I'm getting error with latest master

"Uncaught Error: Failed to create an instance of 'config:environment'. Most likely an improperly defined class or an invalid module export.(…)"

**Comment by antulik** [comment]
according to http://discuss.emberjs.com/t/best-practices-accessing-app-config-from-addon-code/7006/8 it should be 

`appInstance.container.lookupFactory('config:environment')`

**Comment by xcambar** [comment]
The current recommandations are to use the new Owner APIs (`Ember.getOwner`). See http://emberjs.com/blog/2015/11/16/ember-2-2-released.html#toc_introducing-owners-and-deprecating-containers for the announcement and https://github.com/rwjblue/ember-getowner-polyfill for the polyfill

I'll update soon, unless you come up with a PR first ;)

Thank you for your efforts.

**Comment by xcambar** [comment]
Please check out version `0.3.1`, it's been tested against Ember 1.13 and higher and you will not have errors now.
